### ISSUE TITLE
Define routes in .lagoon.yml

### ISSUE THREAD

**Issue by mglaman** [mglaman/contribkanban.com#138]
The GoLive docs specify to allow insecure and non-insecure redirects and then apply once provisioned

```
environments:
  master:
    routes:
      - nginx:
        - example.com
            tls-acme: 'false'
            insecure: Allow
        - www.example.com:
            tls-acme: 'false'
            insecure: Allow
```

and then

```
environments:
  master:
    routes:
      - nginx:
        - example.com
            tls-acme: 'true'
            insecure: Redirect
        - www.example.com:
            tls-acme: 'true'
            insecure: Redirect
```

However, I have seen examples which have just `varnish` and not `nginx.`

- [x] Convert the varnish route to nginx
- [x] ensure tls-acme is false and insecure is Allow
