### ISSUE TITLE
post-rollout for installing sample database deleted production database

### ISSUE THREAD

**Issue by mglaman** [mglaman/contribkanban.com#379]
The following post-rollout hook deleted the database in production somehow, on one single deployment. No others after

```yaml
  - run:
      command: |
        if [[ -n ${LAGOON_PR_BASE_BRANCH} ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
            ./bin/drush -y site-install --account-pass=admin
        fi
      name: If this is a pull request, install the database.
      service: cli
```
